
name: Debug Integration Tests

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug info
      run: |
        echo "Comment body: ${{ github.event.comment.body }}"
        echo "Is PR: ${{ github.event.issue.pull_request != null }}"
        echo "Contains trigger: ${{ contains(github.event.comment.body, '/run-tests') }}"
        echo "Event type: ${{ github.event_name }}"
        echo "Issue number: ${{ github.event.issue.number }}"
  
  test:
    runs-on: ubuntu-latest
    needs: debug
    if: contains(github.event.comment.body, '/run-tests') && github.event.issue.pull_request != null
    
    steps:
    - name: Just a test
      run: echo "Tests would run here!"