name: Integration Tests

on:
  push:

jobs:
  setup:
    uses: ./.github/workflows/test-setup.yml

  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Playwright tests
      env:
        BRANCH: ${{ needs.setup.outputs.branch }}
        BASE_URL: https://${{ needs.setup.outputs.branch }}--vitamix--aemsites.aem.network
      run: npx playwright test --reporter=html

  test-mobile:
    needs: setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Playwright tests on mobile
      env:
        BRANCH: ${{ needs.setup.outputs.branch }}
        BASE_URL: https://${{ needs.setup.outputs.branch }}--vitamix--aemsites.aem.network
      run: npx playwright test --project="Mobile Chrome"